In [6]:
import numpy as np 
import pandas as pd
import requests
import json

## Cocktail DB Example

In [21]:
url = 'http://www.thecocktaildb.com/api/json/v1/1/filter.php?c=Cocktail'

r = requests.get(url)
r

In [22]:
myjson = json.loads(r.text)
myjson

{'drinks': [{'strDrink': '155 Belmont',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yqvvqs1475667388.jpg',
   'idDrink': '15346'},
  {'strDrink': '57 Chevy with a White License Plate',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qyyvtu1468878544.jpg',
   'idDrink': '14029'},
  {'strDrink': '747 Drink',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/i9suxb1582474926.jpg',
   'idDrink': '178318'},
  {'strDrink': '9 1/2 Weeks',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xvwusr1472669302.jpg',
   'idDrink': '16108'},
  {'strDrink': "A Gilligan's Island",
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wysqut1461867176.jpg',
   'idDrink': '16943'},
  {'strDrink': 'A True Amaretto Sour',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rptuxy1472669372.jpg',
   'idDrink': '17005'},
  {'strDrink': 'A.D.M. (After Dinner Mint)',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ruxuvp1472669600.jpg',
   'idDrink': '14560'},
  {'strDrink': 'A1',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg',
   'idDrink': '17222'},
  {'strDrink': 'Abbey Martini',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/2mcozt1504817403.jpg',
   'idDrink': '17223'},
  {'strDrink': 'Absolut Summertime',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/trpxxs1472669662.jpg',
   'idDrink': '14107'},
  {'strDrink': 'Absolutely Fabulous',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/abcpwr1504817734.jpg',
   'idDrink': '17224'},
  {'strDrink': 'Absolutly Screwed Up',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yvxrwv1472669728.jpg',
   'idDrink': '16134'},
  {'strDrink': 'Ace',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/l3cd7f1504818306.jpg',
   'idDrink': '17225'},
  {'strDrink': 'Adam & Eve',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vfeumw1504819077.jpg',
   'idDrink': '17226'},
  {'strDrink': 'Addington',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ib0b7g1504818925.jpg',
   'idDrink': '17227'},
  {'strDrink': 'Addison',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yzva7x1504820300.jpg',
   'idDrink': '17228'},
  {'strDrink': 'Addison Special',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/4vo5651493068493.jpg',
   'idDrink': '14272'},
  {'strDrink': 'Adios Amigos Cocktail',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/8nk2mp1504819893.jpg',
   'idDrink': '17229'},
  {'strDrink': 'Afterglow',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vuquyv1468876052.jpg',
   'idDrink': '12560'},
  {'strDrink': 'Alice Cocktail',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qyqtpv1468876144.jpg',
   'idDrink': '12562'},
  {'strDrink': 'Amaretto fizz',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/92h3jz1582474310.jpg',
   'idDrink': '178321'},
  {'strDrink': 'Aperol Spritz',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/iloasq1587661955.jpg',
   'idDrink': '178325'},
  {'strDrink': 'Apple Highball',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/66mt9b1619695719.jpg',
   'idDrink': '178353'},
  {'strDrink': 'Apple Karate',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/syusvw1468876634.jpg',
   'idDrink': '12564'},
  {'strDrink': 'Applejack',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/sutyqp1479209062.jpg',
   'idDrink': '16311'},
  {'strDrink': 'Aquamarine',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/zvsre31572902738.jpg',
   'idDrink': '178319'},
  {'strDrink': 'Arizona Stingers',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/y7w0721493068255.jpg',
   'idDrink': '14584'},
  {'strDrink': 'Arizona Twister',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ido1j01493068134.jpg',
   'idDrink': '17074'},
  {'strDrink': 'Army special',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/55muhh1493068062.jpg',
   'idDrink': '17066'},
  {'strDrink': 'Autumn Garibaldi',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ne7re71604179012.jpg',
   'idDrink': '178337'},
  {'strDrink': 'Aviation',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/trbplb1606855233.jpg',
   'idDrink': '17180'},
  {'strDrink': 'Bahama Mama',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/tyb4a41515793339.jpg',
   'idDrink': '17267'},
  {'strDrink': 'Banana Cream Pi',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/m5p67n1582474609.jpg',
   'idDrink': '178320'},
  {'strDrink': "Bee's Knees",
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/tx8ne41582475326.jpg',
   'idDrink': '178317'},
  {'strDrink': 'Bijou',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rysb3r1513706985.jpg',
   'idDrink': '17254'},
  {'strDrink': 'Blue Hurricane',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/nwx02s1515795822.jpg',
   'idDrink': '17268'},
  {'strDrink': 'Blueberry Mojito',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/07iep51598719977.jpg',
   'idDrink': '178336'},
  {'strDrink': 'Bombay Cassis',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/h1e0e51510136907.jpg',
   'idDrink': '17242'},
  {'strDrink': 'Bora Bora',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xwuqvw1473201811.jpg',
   'idDrink': '12572'},
  {'strDrink': 'Boulevardier',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/km84qi1513705868.jpg',
   'idDrink': '17251'},
  {'strDrink': 'Bounty Hunter',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/t8bgxl1596018175.jpg',
   'idDrink': '178331'},
  {'strDrink': 'Brigadier',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/nl89tf1518947401.jpg',
   'idDrink': '17825'},
  {'strDrink': 'Broadside',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/l2o6xu1582476870.jpg',
   'idDrink': '178311'},
  {'strDrink': 'Brooklyn',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ojsezf1582477277.jpg',
   'idDrink': '178310'},
  {'strDrink': 'Butterfly Effect',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ht3hnk1619704289.jpg',
   'idDrink': '178356'},
  {'strDrink': "Captain Kidd's Punch",
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/d83spj1596017390.jpg',
   'idDrink': '178329'},
  {'strDrink': 'Cherry Electric Lemonade',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/tquyyt1451299548.jpg',
   'idDrink': '17174'},
  {'strDrink': 'Cocktail Horse’s Neck',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/4vobt21643844913.jpg',
   'idDrink': '178369'},
  {'strDrink': 'Corn n Oil',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/pk6dwi1592767243.jpg',
   'idDrink': '17830'},
  {'strDrink': 'Corpse Reviver',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/gifgao1513704334.jpg',
   'idDrink': '17250'},
  {'strDrink': 'Cosmopolitan',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/kpsajh1504368362.jpg',
   'idDrink': '17196'},
  {'strDrink': 'Cosmopolitan Martini',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/upxxpq1439907580.jpg',
   'idDrink': '14133'},
  {'strDrink': 'Cream Soda',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yqstxr1479209367.jpg',
   'idDrink': '14608'},
  {'strDrink': 'Dark Caipirinha',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/uwstrx1472406058.jpg',
   'idDrink': '17177'},
  {'strDrink': 'Death in the Afternoon',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/y7s3rh1598719574.jpg',
   'idDrink': '178334'},
  {'strDrink': 'Dirty Martini',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vcyvpq1485083300.jpg',
   'idDrink': '17181'},
  {'strDrink': 'Dry Martini',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/6ck9yi1589574317.jpg',
   'idDrink': '11005'},
  {'strDrink': "Duchamp's Punch",
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/g51naw1485084685.jpg',
   'idDrink': '17182'},
  {'strDrink': 'Elderflower Caipirinha',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/dif7a31614006331.jpg',
   'idDrink': '178346'},
  {'strDrink': "Empellón Cocina's Fat-Washed Mezcal",
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/osgvxt1513595509.jpg',
   'idDrink': '17246'},
  {'strDrink': 'Espresso Martini',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/n0sx531504372951.jpg',
   'idDrink': '17212'},
  {'strDrink': 'Espresso Rumtini',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/acvf171561574403.jpg',
   'idDrink': '178309'},
  {'strDrink': 'Figgy Thyme',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/pbw4e51606766578.jpg',
   'idDrink': '178344'},
  {'strDrink': 'Flaming Lamborghini',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yywpss1461866587.jpg',
   'idDrink': '16485'},
  {'strDrink': 'French Martini',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/clth721504373134.jpg',
   'idDrink': '17213'},
  {'strDrink': 'French Negroni',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/x8lhp41513703167.jpg',
   'idDrink': '17248'},
  {'strDrink': 'Frosé',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/b4cadp1619695347.jpg',
   'idDrink': '178352'},
  {'strDrink': 'Funk and Soul',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qtv83q1596015790.jpg',
   'idDrink': '178328'},
  {'strDrink': 'Gagliardo',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/lyloe91487602877.jpg',
   'idDrink': '12758'},
  {'strDrink': 'Garibaldi Negroni',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/kb4bjg1604179771.jpg',
   'idDrink': '178340'},
  {'strDrink': 'Gimlet',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/3xgldt1513707271.jpg',
   'idDrink': '17255'},
  {'strDrink': 'Gin and Soda',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/nzlyc81605905755.jpg',
   'idDrink': '178342'},
  {'strDrink': 'Gin Basil Smash',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/jqh2141572807327.jpg',
   'idDrink': '178314'},
  {'strDrink': 'Gin Lemon',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/6gdohq1681212476.jpg',
   'idDrink': '178366'},
  {'strDrink': 'Gin Rickey',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/s00d6f1504883945.jpg',
   'idDrink': '17230'},
  {'strDrink': 'Gin Tonic',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qcgz0t1643821443.jpg',
   'idDrink': '178365'},
  {'strDrink': 'Greyhound',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/g5upn41513706732.jpg',
   'idDrink': '17252'},
  {'strDrink': 'Honey Bee',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vu8l7t1582475673.jpg',
   'idDrink': '178316'},
  {'strDrink': 'Hot Toddy',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ggx0lv1613942306.jpg',
   'idDrink': '178345'},
  {'strDrink': "Hunter's Moon",
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/t0iugg1509556712.jpg',
   'idDrink': '17239'},
  {'strDrink': 'Imperial Cocktail',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/bcsj2e1487603625.jpg',
   'idDrink': '12706'},
  {'strDrink': 'Irish Curdling Cow',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yrhutv1503563730.jpg',
   'idDrink': '16987'},
  {'strDrink': 'Jitterbug',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wwqvrq1441245318.jpg',
   'idDrink': '16178'},
  {'strDrink': 'Kiwi Martini',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/bmxmyq1630407098.jpg',
   'idDrink': '178359'},
  {'strDrink': 'Lazy Coconut Paloma',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rytuex1598719770.jpg',
   'idDrink': '178335'},
  {'strDrink': 'Lemon Drop',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/mtpxgk1504373297.jpg',
   'idDrink': '14366'},
  {'strDrink': 'Lemon Elderflower Spritzer',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/125w0o1630407389.jpg',
   'idDrink': '178360'},
  {'strDrink': 'Malibu Twister',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/2dwae41504885321.jpg',
   'idDrink': '15224'},
  {'strDrink': 'Mango Mojito',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wfqmgm1630406820.jpg',
   'idDrink': '178358'},
  {'strDrink': 'Manhattan',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yk70e31606771240.jpg',
   'idDrink': '11008'},
  {'strDrink': 'Martinez 2',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/fs6kiq1513708455.jpg',
   'idDrink': '17256'},
  {'strDrink': 'Martinez Cocktail',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wwxwvr1439906452.jpg',
   'idDrink': '11720'},
  {'strDrink': 'Martini',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/71t8581504353095.jpg',
   'idDrink': '11728'},
  {'strDrink': 'Mary Pickford',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/f9erqb1504350557.jpg',
   'idDrink': '17188'},
  {'strDrink': 'Mauresque',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/duwfa11686236556.jpg',
   'idDrink': '178370'},
  {'strDrink': 'Miami Vice',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qvuyqw1441208955.jpg',
   'idDrink': '13936'},
  {'strDrink': 'Michelada',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/u736bd1605907086.jpg',
   'idDrink': '178343'},
  {'strDrink': 'Midnight Mint',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/svuvrq1441208310.jpg',
   'idDrink': '14842'},
  {'strDrink': 'Mojito',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/metwgh1606770327.jpg',
   'idDrink': '11000'},
  {'strDrink': 'Mojito Extra',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vwxrsw1478251483.jpg',
   'idDrink': '15841'}]}

In [23]:
myjson['drinks'][0]['strDrinkThumb']

'https://www.thecocktaildb.com/images/media/drink/yqvvqs1475667388.jpg'

**Records**: the list of equivalently formatted dictionaries that you want to become ROWS in a dataframe

**Record path**: the sequence of JSON keys you need to delve into to get to the records

In this case, the record path is just `'drinks'`

In [24]:
cocktail_df = pd.json_normalize(myjson, record_path=['drinks'])
cocktail_df

,strDrink,strDrinkThumb,idDrink
0,155 Belmont,https://www.thecocktaildb.com/images/media/dri...,15346
1,57 Chevy with a White License Plate,https://www.thecocktaildb.com/images/media/dri...,14029
2,747 Drink,https://www.thecocktaildb.com/images/media/dri...,178318
3,9 1/2 Weeks,https://www.thecocktaildb.com/images/media/dri...,16108
4,A Gilligan's Island,https://www.thecocktaildb.com/images/media/dri...,16943
...,...,...,...
95,Miami Vice,https://www.thecocktaildb.com/images/media/dri...,13936
96,Michelada,https://www.thecocktaildb.com/images/media/dri...,178343
97,Midnight Mint,https://www.thecocktaildb.com/images/media/dri...,14842
98,Mojito,https://www.thecocktaildb.com/images/media/dri...,11000
99,Mojito Extra,https://www.thecocktaildb.com/images/media/dri...,15841

## Wikipedia API

In [25]:
url = 'https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=Virginia&format=json&srlimit=500'
r = requests.get(url)
r

In [28]:
myjson = r.json()
wiki_df = pd.json_normalize(myjson, record_path=['query', 'search'])
wiki_df

,ns,title,pageid,size,wordcount,snippet,timestamp
0,0,Virginia,32432,287974,24676,"<span class=""searchmatch"">Virginia</span>, off...",2025-01-25T07:28:48Z
1,0,West Virginia,32905,184361,18090,"West <span class=""searchmatch"">Virginia</span>...",2025-01-21T13:04:57Z
2,0,Virgínia,1392216,2105,32,"<span class=""searchmatch"">Virgínia</span> is a...",2024-11-11T14:52:44Z
3,0,Virginia Woolf,32742,159563,16541,"Adeline <span class=""searchmatch"">Virginia</sp...",2025-01-26T05:36:08Z
4,0,"Virginia Beach, Virginia",91239,153586,13654,"<span class=""searchmatch"">Virginia</span> Beac...",2025-01-28T18:28:12Z
...,...,...,...,...,...,...,...
495,0,Culture of Virginia,21241504,26763,2653,"Culture of <span class=""searchmatch"">Virginia<...",2024-07-29T03:18:15Z
496,0,Golden Virginia,5142111,4644,528,"Golden <span class=""searchmatch"">Virginia</spa...",2024-07-14T17:55:03Z
497,0,Virginia Defense Force,2668507,30832,3370,"The <span class=""searchmatch"">Virginia</span> ...",2025-01-02T18:46:56Z
498,0,West Virginia Mountaineers women's basketball,40042238,22666,331,"The West <span class=""searchmatch"">Virginia</s...",2024-11-17T12:55:18Z
499,0,Virginia Clay-Clopton,6696332,11092,1393,"<span class=""searchmatch"">Virginia</span> Clay...",2025-01-17T10:48:24Z

## News API

**Warning**: DO NOT DO THIS

Don't paste an API key into your code. You have to hide it with a .env file. More on that in module 4.

API key: 6ddd1df1e2234e799fb86e2c2e9deca5

In [29]:
newskey = '6ddd1df1e2234e799fb86e2c2e9deca5'

In [34]:
url = 'https://newsapi.org/v2/everything'
params = {'apiKey':newskey,
          'q':'Virgen de Guadalupe'}
r = requests.get(url, params=params)
r

In [37]:
myjson = r.json()
news_df = pd.json_normalize(myjson, record_path=['articles'])
news_df

,author,title,description,url,urlToImage,publishedAt,content,source.id,source.name
0,Miguel Solo,Cómo la telenovela más famosa de México usó la...,"Para los más asiduos en redes, no sería extrañ...",https://www.espinof.com/series-de-ficcion/como...,https://i.blogs.es/4e5b09/azul/840_560.jpeg,2025-01-20T20:31:47Z,"Para los más asiduos en redes, no sería extrañ...",None,Espinof.com
1,Joel Calata,Así luce ahora uno de los pueblos más bonitos ...,"Ubicado en el corazón del desierto mexicano, e...",https://www.trendencias.com/mexico/asi-luce-ah...,https://i.blogs.es/328e94/2023-10-20-copia/840...,2025-01-27T17:39:12Z,"Ubicado en el corazón del desierto mexicano, e...",None,Trendencias.com
2,Suzanne Sease,The Art of the Personal Project: Amanda Lopez,The Art of the Personal Project is a crucial e...,https://www.aphotoeditor.com/2025/01/10/the-ar...,https://www.aphotoeditor.com/wp-content/upload...,2025-01-10T15:00:01Z,The Art of the Personal Project is a crucial e...,None,Aphotoeditor.com
3,"DEMOS, Desarrollo de Medios, S.A. de C.V.",Cabildo sesiona en iglesia y da llaves de la c...,"Guadalupe, Zac., Sara Hernández y Rocío Hernán...",https://www.jornada.com.mx/2025/01/14/estados/...,https://www.jornada.com.mx/2025/01/14/fotos/02...,2025-01-14T09:35:09Z,Periódico La JornadaMartes 14 de enero de 2025...,None,Jornada.com.mx
4,(abc),Horarios e itinerarios del rosario extraordina...,La Virgen del Rocío de la Redención protagoniz...,https://www.abc.es/sevilla/pasionensevilla/not...,https://s3.abcstatics.com/abc/www/multimedia/s...,2025-01-17T23:58:18Z,La Virgen del Rocío de la Redención protagoniz...,None,Www.abc.es
...,...,...,...,...,...,...,...,...,...
73,None,La Junta valora las 345 actuaciones en centros...,"La consejera de Educación, Ciencia y Formación...",https://www.europapress.es/extremadura/noticia...,https://img.europapress.es/fotoweb/fotonoticia...,2025-01-20T10:56:11Z,"MÉRIDA, 20 Ene. (EUROPA PRESS) - \r\n La con...",None,Europapress.es
74,Karina Lopez,Elina Costantini súper embarazada: las fotos e...,Eduardo Costantini y su mujer bajaron a la pla...,https://caras.perfil.com/noticias/celebridades...,https://fotos.perfil.com/2025/01/07/trim/1140/...,2025-01-08T18:13:25Z,Elina Costantini (34) sabía que la Virgen de G...,None,Perfil.com
75,La Voz,Calendario laboral del 2025 de la provincia de...,Además de los días de fiesta nacionales y auto...,https://www.lavozdegalicia.es/noticia/economia...,https://img.lavdg.com/sc/poKjlqoCfw-wl-pikcVNJ...,2025-01-10T16:38:00Z,"Aunque algunos ya han pasado, el calendario la...",None,Lavozdegalicia.es
76,Guadalupe Fernández Viero,El Hollywood argentino. Fue creado por cuatro ...,En los estudios Lumiton se produjeron grandes ...,https://www.lanacion.com.ar/lifestyle/el-holly...,https://resizer.glanacion.com/resizer/v2/tecni...,2025-01-27T14:00:18Z,Es 1930 y en Munro predomina el silencio. Un b...,la-nacion,La Nacion
77,(abc),Multitudinaria celebración en Toledo del Año J...,"Muchas decenas de sacerdotes de la diócesis, u...",https://www.abc.es/espana/castilla-la-mancha/t...,https://s1.abcstatics.com/abc/www/multimedia/e...,2024-12-29T18:29:03Z,"Muchas decenas de sacerdotes de la diócesis, u...",None,Www.abc.es

In [1]:
import pandas as pd
import json
import requests
users = requests.get("https://jsonplaceholder.typicode.com/users")
users = json.loads(users.text)

In [2]:
users

[{'id': 1,
  'name': 'Leanne Graham',
  'username': 'Bret',
  'email': 'Sincere@april.biz',
  'address': {'street': 'Kulas Light',
   'suite': 'Apt. 556',
   'city': 'Gwenborough',
   'zipcode': '92998-3874',
   'geo': {'lat': '-37.3159', 'lng': '81.1496'}},
  'phone': '1-770-736-8031 x56442',
  'website': 'hildegard.org',
  'company': {'name': 'Romaguera-Crona',
   'catchPhrase': 'Multi-layered client-server neural-net',
   'bs': 'harness real-time e-markets'}},
 {'id': 2,
  'name': 'Ervin Howell',
  'username': 'Antonette',
  'email': 'Shanna@melissa.tv',
  'address': {'street': 'Victor Plains',
   'suite': 'Suite 879',
   'city': 'Wisokyburgh',
   'zipcode': '90566-7771',
   'geo': {'lat': '-43.9509', 'lng': '-34.4618'}},
  'phone': '010-692-6593 x09125',
  'website': 'anastasia.net',
  'company': {'name': 'Deckow-Crist',
   'catchPhrase': 'Proactive didactic contingency',
   'bs': 'synergize scalable supply-chains'}},
 {'id': 3,
  'name': 'Clementine Bauch',
  'username': 'Samantha',
  'email': 'Nathan@yesenia.net',
  'address': {'street': 'Douglas Extension',
   'suite': 'Suite 847',
   'city': 'McKenziehaven',
   'zipcode': '59590-4157',
   'geo': {'lat': '-68.6102', 'lng': '-47.0653'}},
  'phone': '1-463-123-4447',
  'website': 'ramiro.info',
  'company': {'name': 'Romaguera-Jacobson',
   'catchPhrase': 'Face to face bifurcated interface',
   'bs': 'e-enable strategic applications'}},
 {'id': 4,
  'name': 'Patricia Lebsack',
  'username': 'Karianne',
  'email': 'Julianne.OConner@kory.org',
  'address': {'street': 'Hoeger Mall',
   'suite': 'Apt. 692',
   'city': 'South Elvis',
   'zipcode': '53919-4257',
   'geo': {'lat': '29.4572', 'lng': '-164.2990'}},
  'phone': '493-170-9623 x156',
  'website': 'kale.biz',
  'company': {'name': 'Robel-Corkery',
   'catchPhrase': 'Multi-tiered zero tolerance productivity',
   'bs': 'transition cutting-edge web services'}},
 {'id': 5,
  'name': 'Chelsey Dietrich',
  'username': 'Kamren',
  'email': 'Lucio_Hettinger@annie.ca',
  'address': {'street': 'Skiles Walks',
   'suite': 'Suite 351',
   'city': 'Roscoeview',
   'zipcode': '33263',
   'geo': {'lat': '-31.8129', 'lng': '62.5342'}},
  'phone': '(254)954-1289',
  'website': 'demarco.info',
  'company': {'name': 'Keebler LLC',
   'catchPhrase': 'User-centric fault-tolerant solution',
   'bs': 'revolutionize end-to-end systems'}},
 {'id': 6,
  'name': 'Mrs. Dennis Schulist',
  'username': 'Leopoldo_Corkery',
  'email': 'Karley_Dach@jasper.info',
  'address': {'street': 'Norberto Crossing',
   'suite': 'Apt. 950',
   'city': 'South Christy',
   'zipcode': '23505-1337',
   'geo': {'lat': '-71.4197', 'lng': '71.7478'}},
  'phone': '1-477-935-8478 x6430',
  'website': 'ola.org',
  'company': {'name': 'Considine-Lockman',
   'catchPhrase': 'Synchronised bottom-line interface',
   'bs': 'e-enable innovative applications'}},
 {'id': 7,
  'name': 'Kurtis Weissnat',
  'username': 'Elwyn.Skiles',
  'email': 'Telly.Hoeger@billy.biz',
  'address': {'street': 'Rex Trail',
   'suite': 'Suite 280',
   'city': 'Howemouth',
   'zipcode': '58804-1099',
   'geo': {'lat': '24.8918', 'lng': '21.8984'}},
  'phone': '210.067.6132',
  'website': 'elvis.io',
  'company': {'name': 'Johns Group',
   'catchPhrase': 'Configurable multimedia task-force',
   'bs': 'generate enterprise e-tailers'}},
 {'id': 8,
  'name': 'Nicholas Runolfsdottir V',
  'username': 'Maxime_Nienow',
  'email': 'Sherwood@rosamond.me',
  'address': {'street': 'Ellsworth Summit',
   'suite': 'Suite 729',
   'city': 'Aliyaview',
   'zipcode': '45169',
   'geo': {'lat': '-14.3990', 'lng': '-120.7677'}},
  'phone': '586.493.6943 x140',
  'website': 'jacynthe.com',
  'company': {'name': 'Abernathy Group',
   'catchPhrase': 'Implemented secondary concept',
   'bs': 'e-enable extensible e-tailers'}},
 {'id': 9,
  'name': 'Glenna Reichert',
  'username': 'Delphine',
  'email': 'Chaim_McDermott@dana.io',
  'address': {'street': 'Dayna Park',
   'suite': 'Suite 449',
   'city': 'Bartholomebury',
   'zipcode': '76495-3109',
   'geo': {'lat': '24.6463', 'lng': '-168.8889'}},
  'phone': '(775)976-6794 x41206',
  'website': 'conrad.com',
  'company': {'name': 'Yost and Sons',
   'catchPhrase': 'Switchable contextually-based project',
   'bs': 'aggregate real-time technologies'}},
 {'id': 10,
  'name': 'Clementina DuBuque',
  'username': 'Moriah.Stanton',
  'email': 'Rey.Padberg@karina.biz',
  'address': {'street': 'Kattie Turnpike',
   'suite': 'Suite 198',
   'city': 'Lebsackbury',
   'zipcode': '31428-2261',
   'geo': {'lat': '-38.2386', 'lng': '57.2232'}},
  'phone': '024-648-3804',
  'website': 'ambrose.net',
  'company': {'name': 'Hoeger LLC',
   'catchPhrase': 'Centralized empowering task-force',
   'bs': 'target end-to-end models'}}]

In [4]:
users[5]['company']['catchPhrase']

'Synchronised bottom-line interface'

In [8]:
users[9]['address']['geo']['lng']

'57.2232'

In [10]:
data1 = pd.DataFrame.from_records(users)
data2 = pd.json_normalize(users)

In [11]:
data1

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

In [12]:
data2

,id,name,username,email,phone,website,address.street,address.suite,address.city,address.zipcode,address.geo.lat,address.geo.lng,company.name,company.catchPhrase,company.bs
0,1,Leanne Graham,Bret,Sincere@april.biz,1-770-736-8031 x56442,hildegard.org,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,010-692-6593 x09125,anastasia.net,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,1-463-123-4447,ramiro.info,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,493-170-9623 x156,kale.biz,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990,Robel-Corkery,Multi-tiered zero tolerance productivity,transition cutting-edge web services
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,(254)954-1289,demarco.info,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342,Keebler LLC,User-centric fault-tolerant solution,revolutionize end-to-end systems
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,1-477-935-8478 x6430,ola.org,Norberto Crossing,Apt. 950,South Christy,23505-1337,-71.4197,71.7478,Considine-Lockman,Synchronised bottom-line interface,e-enable innovative applications
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,210.067.6132,elvis.io,Rex Trail,Suite 280,Howemouth,58804-1099,24.8918,21.8984,Johns Group,Configurable multimedia task-force,generate enterprise e-tailers
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,586.493.6943 x140,jacynthe.com,Ellsworth Summit,Suite 729,Aliyaview,45169,-14.3990,-120.7677,Abernathy Group,Implemented secondary concept,e-enable extensible e-tailers
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,(775)976-6794 x41206,conrad.com,Dayna Park,Suite 449,Bartholomebury,76495-3109,24.6463,-168.8889,Yost and Sons,Switchable contextually-based project,aggregate real-time technologies
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,024-648-3804,ambrose.net,Kattie Turnpike,Suite 198,Lebsackbury,31428-2261,-38.2386,57.2232,Hoeger LLC,Centralized empowering task-force,target end-to-end models

In [13]:
data1 = pd.json_normalize(users, max_level=0)
data2 = pd.json_normalize(users, max_level=1)
data3 = pd.json_normalize(users, max_level=2)

In [14]:
data1

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

In [15]:
data2

,id,name,username,email,phone,website,address.street,address.suite,address.city,address.zipcode,address.geo,company.name,company.catchPhrase,company.bs
0,1,Leanne Graham,Bret,Sincere@april.biz,1-770-736-8031 x56442,hildegard.org,Kulas Light,Apt. 556,Gwenborough,92998-3874,"{'lat': '-37.3159', 'lng': '81.1496'}",Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,010-692-6593 x09125,anastasia.net,Victor Plains,Suite 879,Wisokyburgh,90566-7771,"{'lat': '-43.9509', 'lng': '-34.4618'}",Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,1-463-123-4447,ramiro.info,Douglas Extension,Suite 847,McKenziehaven,59590-4157,"{'lat': '-68.6102', 'lng': '-47.0653'}",Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,493-170-9623 x156,kale.biz,Hoeger Mall,Apt. 692,South Elvis,53919-4257,"{'lat': '29.4572', 'lng': '-164.2990'}",Robel-Corkery,Multi-tiered zero tolerance productivity,transition cutting-edge web services
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,(254)954-1289,demarco.info,Skiles Walks,Suite 351,Roscoeview,33263,"{'lat': '-31.8129', 'lng': '62.5342'}",Keebler LLC,User-centric fault-tolerant solution,revolutionize end-to-end systems
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,1-477-935-8478 x6430,ola.org,Norberto Crossing,Apt. 950,South Christy,23505-1337,"{'lat': '-71.4197', 'lng': '71.7478'}",Considine-Lockman,Synchronised bottom-line interface,e-enable innovative applications
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,210.067.6132,elvis.io,Rex Trail,Suite 280,Howemouth,58804-1099,"{'lat': '24.8918', 'lng': '21.8984'}",Johns Group,Configurable multimedia task-force,generate enterprise e-tailers
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,586.493.6943 x140,jacynthe.com,Ellsworth Summit,Suite 729,Aliyaview,45169,"{'lat': '-14.3990', 'lng': '-120.7677'}",Abernathy Group,Implemented secondary concept,e-enable extensible e-tailers
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,(775)976-6794 x41206,conrad.com,Dayna Park,Suite 449,Bartholomebury,76495-3109,"{'lat': '24.6463', 'lng': '-168.8889'}",Yost and Sons,Switchable contextually-based project,aggregate real-time technologies
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,024-648-3804,ambrose.net,Kattie Turnpike,Suite 198,Lebsackbury,31428-2261,"{'lat': '-38.2386', 'lng': '57.2232'}",Hoeger LLC,Centralized empowering task-force,target end-to-end models

In [16]:
data3

,id,name,username,email,phone,website,address.street,address.suite,address.city,address.zipcode,address.geo.lat,address.geo.lng,company.name,company.catchPhrase,company.bs
0,1,Leanne Graham,Bret,Sincere@april.biz,1-770-736-8031 x56442,hildegard.org,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,010-692-6593 x09125,anastasia.net,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,1-463-123-4447,ramiro.info,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,493-170-9623 x156,kale.biz,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990,Robel-Corkery,Multi-tiered zero tolerance productivity,transition cutting-edge web services
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,(254)954-1289,demarco.info,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342,Keebler LLC,User-centric fault-tolerant solution,revolutionize end-to-end systems
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,1-477-935-8478 x6430,ola.org,Norberto Crossing,Apt. 950,South Christy,23505-1337,-71.4197,71.7478,Considine-Lockman,Synchronised bottom-line interface,e-enable innovative applications
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,210.067.6132,elvis.io,Rex Trail,Suite 280,Howemouth,58804-1099,24.8918,21.8984,Johns Group,Configurable multimedia task-force,generate enterprise e-tailers
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,586.493.6943 x140,jacynthe.com,Ellsworth Summit,Suite 729,Aliyaview,45169,-14.3990,-120.7677,Abernathy Group,Implemented secondary concept,e-enable extensible e-tailers
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,(775)976-6794 x41206,conrad.com,Dayna Park,Suite 449,Bartholomebury,76495-3109,24.6463,-168.8889,Yost and Sons,Switchable contextually-based project,aggregate real-time technologies
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,024-648-3804,ambrose.net,Kattie Turnpike,Suite 198,Lebsackbury,31428-2261,-38.2386,57.2232,Hoeger LLC,Centralized empowering task-force,target end-to-end models